### ISSUE TITLE
Do some next level brand work

### ISSUE THREAD

**Issue by danirabbit** [bartzaalberg/snaptastic#12]
Started playing around with the idea of really going hard on the Ubuntu brand here:

![screenshot from 2018-01-30 21 17 13](https://user-images.githubusercontent.com/7277719/35606295-24322c12-0603-11e8-96d7-c6a32c0cb9d6.png)

- [x] Set the title label and image colors to white with a dark orange shadow
- [x] Use the Ubuntu font for header labels
- [x] Use the accent color for .h2
- [x] Use a branded open icon

Here's the CSS I added, but there will probably be more needed to make this work on Loki:

```
@define-color textColorPrimary #fff;
@define-color textColorPrimaryShadow shade(@colorPrimary, 0.85);

.h1,
.h2 {
    font-family: Ubuntu;
}

.h2 {
    color: @colorPrimary;
}
```

**Comment by danirabbit** [comment]
Here's the icon: [document-open-ubuntu.svg.zip](https://github.com/bartzaalberg/snaptastic/files/1680519/document-open-ubuntu.svg.zip)

**Comment by unbelievableflavour** [comment]
Almost worked right out of the box! Thanks :) Added it to master
