### ISSUE TITLE
Use GResource for custom icon

### ISSUE THREAD

**Issue by danirabbit** [bartzaalberg/snaptastic#13]
https://github.com/bartzaalberg/snaptastic/blob/279050c211824a90362e0e61ebb886fc7965696d/CMakeLists.txt#L110

Instead of installing this icon to the filesystem, it would be better to use a GResource. TL;DR you want to create a resource xml file, tell cmake to compile it into your app, and then load the resource as a fallback icon theme in your app.

See the following:
https://github.com/elementary/music/blob/master/data/icons/icons.gresource.xml
https://github.com/elementary/music/blob/master/src/CMakeLists.txt#L85
https://github.com/elementary/music/blob/master/src/Application.vala#L51

**Comment by unbelievableflavour** [comment]
Added to master
