### ISSUE TITLE
Open snaps from Snaptastic

### ISSUE THREAD

**Issue by danirabbit** [bartzaalberg/snaptastic#18]
Much like in AppCenter, it would be convenient to have a button to be able to open the app after it has been installed

**Comment by unbelievableflavour** [comment]
Done, added to master

**Comment by peteruithoven** [comment]
Tip: including the issue number in commits will automatically add a link in the issue to that commit. You can even close issues that way, see: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by unbelievableflavour** [comment]
Oh nice. Thanks
