### ISSUE TITLE
Consider using snapd-glib instead of snap command line tool

### ISSUE THREAD

**Issue by robert-ancell** [bartzaalberg/snaptastic#19]
I wonder if you've considered using [snapd-glib](https://github.com/snapcore/snapd-glib) instead of the snap command line tool? This has Vala bindings and will allow you to get better error messages and handle things like progress indication.

I'm the maintainer and happy to help you if you have any questions.

**Comment by unbelievableflavour** [comment]
Oh nice. i didn't know that! i will look into that when i have some spare time :)

**Comment by unbelievableflavour** [comment]
Ok, i might need some help. I can't find any examples of how to use your snapd-glib in vala. And i'm not coding in vala long enough to have the knowledge to make it work by myself. Any tips? hints?

**Comment by danirabbit** [comment]
Snapd Glib is on Valadoc, but there aren't any code samples there: https://valadoc.org/snapd-glib/Snapd.html

**Comment by unbelievableflavour** [comment]
Ah finally. I am booking some progress on this.

**Comment by robert-ancell** [comment]
Sorry, no code samples but there's a bit of an introduction in http://bobthegnome.blogspot.co.nz/2016/08/introducing-snapd-glib.html

**Comment by unbelievableflavour** [comment]
Yes i've used that. Good article. It was alot of help. But i'm stuck at 1 thing. Is there a function to get information from a snap file? Because i can't find a function for it.

**Comment by robert-ancell** [comment]
You can install from a file using `snapd_client_install_stream` but there is not currently any functionality to scan a .snap file for metadata. snapd doesn't provide this, though I think it would be useful for snapd-glib to have functionality like this.

**Comment by unbelievableflavour** [comment]
Yes definitely. Because now i still have to do that the old way :P

**Comment by unbelievableflavour** [comment]
Ok, i think i integrated it. But now i'm getting this error.

 [FATAL 23:54:29.290837] [GLib] g_byte_array_remove_range: assertion 'index_ + length <= array->len' failed
[WARNING 23:54:29.290855] [Snapd] Ignoring unexpected response

I noticed you commenting on it on https://bugs.launchpad.net/ubuntu/+source/gnome-software/+bug/1723362 that it had something to do with snapd-glib. How can i fix this?

**Comment by robert-ancell** [comment]
What version of snapd-glib do you have?

**Comment by unbelievableflavour** [comment]
i tried both libsnapd-glib1 and libsnapd-dev. both gave me the same error. 
And they are on version 1.13-0ubuntu0.16.04.1. That seems like an old version but i have no idea how to update.

**Comment by robert-ancell** [comment]
This bug was fixed in 1.24 - @danrabbit is there an easy way to update the version of snapd-glib in Elementary?

**Comment by danirabbit** [comment]
At the moment we’re just inherited what’s in Ubuntu 16.04. If it would be easily backported, maybe @codygarver can add it to our PPA

**Comment by robert-ancell** [comment]
I've proposed a SRU to push a recent version back to 16.04 - https://bugs.launchpad.net/bugs/1748289

**Comment by unbelievableflavour** [comment]
Is there something like a temporary fix? Or will this be done within a couple of days? Because i would love to continue workin on this :)

**Comment by robert-ancell** [comment]
It's likely to take more than a couple of days; you could:
- Ask @codygarver if he'd be willing to copy the package over to the PPA now. The packaging is in lp:~ubuntu-desktop/snapd-glib/ubuntu-xenial
- Build snapd-glib inside snaptastic.

**Comment by unbelievableflavour** [comment]
So snap-glib is integrated now. I am not running into memory problems anymore, and the updated version of snap-glib will get integrated in a couple of weeks or so, so so that's fine. I am closing this ticket.
