### ISSUE TITLE
Open Snaps from Firefox?

### ISSUE THREAD

**Issue by peteruithoven** [bartzaalberg/snaptastic#20]
Thanks for creating this app! Seeing Slack, Spotify, Skype, Discord all starting to use Snap this app is very welcome. 

Even though it doesn't seem to install the snaps, I thought I'd share the workaround I need to go through to get Snaptastic to open snap links. It's quite similar to what you need to do to have Torrential open magnet links for example. 
1. Go to `about:config`
2. Right click > New > Boolean
3. Enter `network.protocol-handler.expose.snap`
4. Select false
5. Restart browser
6. Opening snap link will open Launch Application popup. Getting Snaptastic in this list might be fixed with #9? For now click on the "Choose..." button. 
7. Go to `/usr/bin/`
8. Select `com.github.bartzaalberg.snaptastic`
9. Click Open
10. Check Remember my choice for snap links

But then Snaptastic opens with the following dialog:
![screenshot from 2018-02-01 23 09 03](https://user-images.githubusercontent.com/523210/35706160-fb964470-07a4-11e8-85bc-0d7fbf9ce521.png)
And when entering my password it navigates to home and nothing seemed to have happened?

I'm not sure how to debug since it's opened from that link.

**Comment by unbelievableflavour** [comment]
I dont think i understand what the question is :P Because at the moment we only support snap files. What you are trying to do is open snaps from the firefox browser? Because we are adding support for that in this ticket. https://github.com/bartzaalberg/snaptastic/issues/9

**Comment by peteruithoven** [comment]
Ah, alright, great! Then the biggest question would be whether it would appear in the Launch Application popup, but I guess we'll see that when #9 is fixed. 
I must admit that it a big part of the issue was sharing the Firefox workaround, so that desktop applications can handle snap links. Unless there is a better way this might be something for the Readme for example?
I guess this is sort of a duplicate of #9, so I'll close it for now.

**Comment by unbelievableflavour** [comment]
I just fixed the implementation already :) it's in master. Still raw so expect some bugs. But i will fix that before next release. The snaps which are installed will automatically show up in the launch application popup also.  Don't need to do anything about that.

**Comment by peteruithoven** [comment]
I meant this Launch Application popup, from Firefox:
![launch application](https://user-images.githubusercontent.com/523210/35732578-32a400cc-081a-11e8-9961-4fb025c8c3bc.png)

**Comment by unbelievableflavour** [comment]
Oh that popup is already showing up :)
