### ISSUE TITLE
Don't link to an app store

### ISSUE THREAD

**Issue by cassidyjames** [bartzaalberg/snaptastic#23]
After a lengthy discussion with the team, we've decided that apps in AppCenter shouldn't link to alternative app stores. We're thinking about the case where someone sees Snaptastic on the homepage, installs and opens it straight from the curated-and-safe AppCenter, clicks the first button in their new safe and curated app, and now is in an entirely uncurated and external app store.

Whereas if a user is manually going to the Snapcraft store or being provided a link on a website, they are more likely to understand that the app is not in any way being provided or supported by elementary. There's more of a disconnect between AppCenter and the uncurated app.

As such, I've had to request changes via the AppCenter Dashboard. Sorry about all of this back-and-forth, we're in uncharted territory here for AppCenter. We've updated [the wiki](https://github.com/elementary/houston/wiki/Before-You-Publish#app-stores) to reflect this clarification as well.

**Comment by unbelievableflavour** [comment]
No problem. I understand the issue. I will remove it immediately and write a new release again.
