### ISSUE TITLE
Headerbar buttons can be toggled?

### ISSUE THREAD

**Issue by peteruithoven** [bartzaalberg/snaptastic#25]
Minor issue, but looks like the Home and Updates buttons can be toggled on and off
![snaptastic buttons](https://user-images.githubusercontent.com/523210/35806600-567aebe2-0a80-11e8-83af-f000f98aca5e.gif)

**Comment by unbelievableflavour** [comment]
I'm not quite sure how to fix this. It would be hacky. Because appcenter doesn't even have a fix for this.

**Comment by unbelievableflavour** [comment]
Apparently this is the way it should work for now. If it is changed in granite i will fix it. Closing for now.

**Comment by peteruithoven** [comment]
Good point, I added this example to the existing issue: https://github.com/elementary/granite/issues/67
