### ISSUE TITLE
Add a snap repository

### ISSUE THREAD

**Issue by aggalex** [bartzaalberg/snaptastic#27]
Make it a snap centre and add a snap repository to download snaps from. Would be safer, faster, and more useful.

**Comment by unbelievableflavour** [comment]
Please check the rules. It is not permitted to release other appstores in the elementary appstore. Also that isn't the way i want to go now. You can go to snapcraft.io If you want a decent store. The application can install apps from that store right from the web. Closing this.

**Comment by Ads20000** [comment]
https://snapcraft.io/0ad (for example) won't let you install 0ad unless you have something which knows how to handle `snap://` links. Presumably this app doesn't use that `snap://` link to download and install a snap? If so then how does it do it? Also does this application keep snaps up-to-date? :) https://uappexplorer.com/snap/ubuntu/0ad would be the correct link to _download_ a snap...

**Comment by peteruithoven** [comment]
See: https://github.com/bartzaalberg/snaptastic/issues/9

**Comment by unbelievableflavour** [comment]
Did you try to click the install button? Because it opens 0ad in snaptastic.

**Comment by Ads20000** [comment]
I'm not on Elementary, so until #31 is completed I can't easily use this app, but I'm a snapcraft forums regular lurker so I'm confused as to how this works if it doesn't use the snap store...

**Comment by unbelievableflavour** [comment]
How this works: you go to snapcraft.io . You go to your favorite app. and click the install button. Then snaptastic opens with the correct snap information about that snap, en let's you install it.

**Comment by Ads20000** [comment]
But where does it pull the snap from, if not from the snap store, which is another appstore to the Elementary one?

**Comment by unbelievableflavour** [comment]
It searches for the snap in the default repository. Which is the one from snapcraft.io

**Comment by silascaxias** [comment]
Guys, someone help me, i using the snaptastic in the elementary. But when i will install something, and i go open it, say that no such file or directory.

**Comment by silascaxias** [comment]
I understood how work it, after install something with the snaptastic, you have to relog, for create the menu icons for you access. Nice app.
