### ISSUE TITLE
Could you make a snap package package for snaptastic?

### ISSUE THREAD

**Issue by ghost** [bartzaalberg/snaptastic#31]
Hi, I really appreciate your work , is a good application
but i don't use elementary OS
could you make a snap package or Flatpak package for snaptastic?
in this way, users can install the application in any linux distribution

please.
thank you.

**Comment by unbelievableflavour** [comment]
I'm still trying to create a snap of my other applications. Which is a little hard. If they are working correctly, i will probably build a snap for snaptastic too. But not right now.

**Comment by ghost** [comment]
i see, i hope that you can build yours applications to snap
thanks

**Comment by unbelievableflavour** [comment]
I'm trying. But i'm running into some problems, so if anyone can help me i would be very gratefull.

**Comment by altntowin** [comment]
i see, i don't know

**Comment by ghost** [comment]
i see , i would like to help you, but i'm not Programmer , but you could ask in the snapcraft forum
https://forum.snapcraft.io/categories?_ga=2.261799305.507343821.1519498963-422570412.1517631232

**Comment by unbelievableflavour** [comment]
I'm sorry but i am not interested in creating a snap for this application anymore. Closing this.
