### ISSUE TITLE
Navigation glitch?

### ISSUE THREAD

**Issue by peteruithoven** [bartzaalberg/snaptastic#32]
I noticed that when  navigating from the Updates page (ListView?) to a snap's page (DetailView?) and then pressing back quickly it seems to start navigating back, but then navigates back to the snap's page:
![snaptastic navigation](https://user-images.githubusercontent.com/523210/36383488-90c7f7ba-158c-11e8-8a27-4832014f87cc.gif)

Maybe it has something to do with the "header" that appears after a delay? Maybe there is a navigation triggered when it appears? I say this because when I wait for this header to appear and then press back there is no issue:
![peek 2018-02-19 15-59](https://user-images.githubusercontent.com/523210/36383951-f7387c62-158d-11e8-9f37-468da911d631.gif)

**Comment by unbelievableflavour** [comment]
Added a fix to master

**Comment by peteruithoven** [comment]
thanks!
