### ISSUE TITLE
There Was a Problem Processing Your Payment

### ISSUE THREAD

**Issue by peteruithoven** [bartzaalberg/snaptastic#33]
I'm getting a generic "There Was a Problem Processing Your Payment" when trying to pay for Snaptastic. I've paid for other apps in the past. I have a dutch (NL) Mastercard.
![image](https://user-images.githubusercontent.com/523210/36591222-8cef4bcc-1891-11e8-9913-2843f1805cee.png)

I've opened issues for other apps before:
- https://github.com/mdh34/quickDocs/issues/13
- https://github.com/lainsce/quilter/issues/76

@btkostner hope it's okay that I mention you, you usually seem the guy to help with these matters.

**Comment by unbelievableflavour** [comment]
Can this be because dashboard is currently down?

**Comment by btkostner** [comment]
It was probably because the API was down for maintenance when you were trying to make a payment. Should be good now.

**Comment by unbelievableflavour** [comment]
@peteruithoven could you try again?

**Comment by peteruithoven** [comment]
I tried again, now I'm getting or the same "There Was a Problem Processing Your Payment"" error or another error: There was a problem processing your payment. 
![screenshot from 2018-02-23 14 06 19](https://user-images.githubusercontent.com/523210/36595542-d2ec5a78-18a2-11e8-9196-06dc5065d070.png)

I tried multiple times. The last time I started it from the command line with `-d` enabled. This showed the following error:

```
[DEBUG 14:08:58.347782] StripeDialog.vala:395: Stripe data:{  "error": {    "type": "invalid_request_error",    "message": "Invalid UTF-8 characters found in POST body: \" 2M\\u001C\\xCF\\u007F\".  For assistance, please contact support@stripe.com.",    "code": "invalid_utf8_in_post_body"  }}
[DEBUG 14:08:58.347969] StripeDialog.vala:480: Stripe error type: invalid_request_error
```

Is it save to share the whole log? I'm not sure if there's sensitive data in there somehow.

Might this be related to https://github.com/elementary/appcenter/issues/602 ?

**Comment by unbelievableflavour** [comment]
Now i'm geting a mail like this "stripe blocked a likely-fraudulent payment.". I have no idea whats going on, because i already received some payments for snaptastic.

**Comment by btkostner** [comment]
Ah, we recently put in a PR that should have fixed that on AppCenter.  I don't think it has made it to release yet.

**Comment by unbelievableflavour** [comment]
Ok, any idea when this will be released?

**Comment by unbelievableflavour** [comment]
@btkostner , could you please let me know when this is fixed?

**Comment by btkostner** [comment]
@bartzaalberg Sorry for the late response. As of right now, AppCenter is targetted for Juno, so we need to backport that one commit and make a new release. Considering our release manager is very busy as of late, it might take a while.

**Comment by unbelievableflavour** [comment]
No problem. Thanks for the response

**Comment by peteruithoven** [comment]
Relevant issue: https://github.com/elementary/appcenter/issues/626, looks like the fix was just released in version [0.29](https://github.com/elementary/appcenter/releases).

**Comment by unbelievableflavour** [comment]
@peteruithoven Could you test if this has worked?

**Comment by peteruithoven** [comment]
Thanks for the reminder. It worked :+1:

**Comment by unbelievableflavour** [comment]
Thanks, and also. Thanks for the donation ^^
