### ISSUE TITLE
Pay Pal

### ISSUE THREAD

**Issue by todotermas** [bartzaalberg/snaptastic#34]
Hi, you can pay by paypal u $ s 3.- Elementary Os
regards
Miguel

**Comment by unbelievableflavour** [comment]
Could you be a bit more clear please?

**Comment by todotermas** [comment]
Thank you For answering, want to buy snaptastic for elementary YOU but want
to pay with PayPal NO with card. Serious well incorporate tambien to PayPal.
Thanks
Saludos cordiales.
Miguel Slamovits

**Comment by zvirdaniel** [comment]
Either he wants to make a donation, or he is confused about the AppStore payments (he wants to buy your application there, but with PayPal instead of paying with a credit card).

**Comment by albe-rosado** [comment]
@bartzaalberg  I think what he is saying, is he would like to be able to pay for apps in the app center with paypal. @todotermas  es eso a lo que te refieres?

**Comment by todotermas** [comment]
Right, for the moment I'm just giving a SUGGESTION because not all the
public likes to put card data.

Thank you



Saludos cordiales
_________________
Miguel Slamovits







2018-03-22 16:06 GMT-03:00 Alberto Rosado <notifications@github.com>:

**Comment by unbelievableflavour** [comment]
Ah ok, i understand. But i'm actually going to make all my applications free. I received a Mac for work, so unfortunately i will have less time on Elementary OS. So this won't be a problem anymore for this application. Closing this
