### ISSUE TITLE
No more Install button on snapcraft store

### ISSUE THREAD

**Issue by peteruithoven** [bartzaalberg/snaptastic#36]
Looks like the install button was removed from the snapcraft.io store:
![screenshot from 2018-03-22 13 15 30](https://user-images.githubusercontent.com/523210/37769964-1cfa8794-2dd3-11e8-8d55-564a3f0d0713.png)

I couldn't find a relevant update / topic in the [Snapcraft forum store category](https://forum.snapcraft.io/c/store). 

I opened an topic on that forum to discuss re-adding the button as alternative option:
https://forum.snapcraft.io/t/no-more-install-button/4613

**Comment by unbelievableflavour** [comment]
Yes... that sucks.. is there anything i can do about this?

**Comment by peteruithoven** [comment]
Not sure, I don't know if you have people you know in that community? If you have thoughts / ideas you could respond in that forum topic. 

(I know posting an issue is a bit weird for this, but didn't know how to reach out otherwise)

**Comment by unbelievableflavour** [comment]
I understand.  Unfortunately i have no one to help in the ubuntu community. So i can't help :(

**Comment by ghost** [comment]
It seems you must use [Ubuntu Core REST API](https://docs.ubuntu.com/core/en/reference/rest)

**Comment by unbelievableflavour** [comment]
Use Core REST API how? Because i don't think this will make an install button show up on the website :P

**Comment by ghost** [comment]
How about using `libsoup` and `json-glib` to query the API and create your own install button in your app?

**Comment by peteruithoven** [comment]
But then it becomes an app center, which isn't allowed currently. Also see:
- https://github.com/bartzaalberg/snaptastic/issues/23
- https://github.com/bartzaalberg/snaptastic/issues/27

**Comment by unbelievableflavour** [comment]
Damn, still can't find a solution to this issue.

**Comment by peteruithoven** [comment]
Update: They re-introduced a install button:
https://forum.snapcraft.io/t/no-more-install-button/4613/19
Clicking *View in Desktop store* will open Snaptastic again :tada:.
![screen shot 2018-05-21 at 11 47 41-fullpage](https://user-images.githubusercontent.com/523210/40301629-e9b4a330-5cec-11e8-9173-980b5599ef4b.png)
![screen shot 2018-05-21 at 11 47 47-fullpage](https://user-images.githubusercontent.com/523210/40301635-ee144322-5cec-11e8-9a21-243aa1f7677c.png)

**Comment by unbelievableflavour** [comment]
Nice! That's good time hear
