### ISSUE TITLE
Sugestion to interface and usability

### ISSUE THREAD

**Issue by Diolinux** [bartzaalberg/snaptastic#38]
Hi, you made a great program and the visual integration with elementary OS is simply gorgeous, however, i have a suggestion to make.

When i wrote about the software at my blog i'd receive a lot of feedback and one of those came with a great idea.

https://www.diolinux.com.br/2018/03/snaptastic-gerenciando-snaps-elementary-os.html

Although the Snaptastic is capable to install and update easily snap from the snapstore, the users still need to go at the site, download the package or click on the "install" button, but there's no indication of that on the program.

For a future updade some of these funcionalities could be implemented.

- a kind of "webview" to install the snaps without leave the snaptastic
or
- a link with simple instrution for "where you can find snaps to download".

A hope this help you, is just some ideas, 

Best Regards.

**Comment by peteruithoven** [comment]
Please see: 
- https://github.com/bartzaalberg/snaptastic/issues/23
- https://github.com/bartzaalberg/snaptastic/issues/17
- https://github.com/bartzaalberg/snaptastic/issues/27
- https://github.com/bartzaalberg/snaptastic/issues/35
- https://github.com/bartzaalberg/snaptastic/issues/36

**Comment by unbelievableflavour** [comment]
Thanks for the awesome blog you wrote about it :). Unfortunately as Peter so kindly pointed out multiple times now. I am not trying to create an app store, it is not allowed by the Elementary OS appcenter rules. So i am closing this.
