### ISSUE TITLE
Snaptastic continues to show "Please wait..." when canceling authentication during updates

### ISSUE THREAD

**Issue by ryonakano** [bartzaalberg/snaptastic#40]
## Actual behavior
When we cancel authentication during updates, Snaptastic continues to show "Please wait..." This may make users thought that the update is proceeding correctly.

## Expected behavior
When we cancel authentication during updates, I think it should return to the app's information page we choose to update. In this bmp example below, this page:

![screenshot_20180516_194656](https://user-images.githubusercontent.com/26003928/40112759-0f550aca-5942-11e8-8877-326a9acfbff1.png)

## Steps to reproduce the behavior

![peek 2018-05-16 19-40](https://user-images.githubusercontent.com/26003928/40112585-77679250-5941-11e8-8bc9-0add7098ad38.gif)

 1. Run Snaptastic and open "Updates" page
 2. Select any snap app and choose "Refresh"
 3. Close the displayed authentication dialog

**Comment by unbelievableflavour** [comment]
This has been long fixed a long time ago. Closing this.
