### ISSUE TITLE
Update for Juno

### ISSUE THREAD

**Issue by peteruithoven** [bartzaalberg/snaptastic#44]
I would love to also see this app on Juno. 
See: [Developer Tips: Updating Your Apps for Juno](https://medium.com/elementaryos/developer-tips-updating-your-apps-for-juno-453c07a5b3a7)

**Comment by unbelievableflavour** [comment]
I will have a look at this as soon as i have some spare time.

**Comment by unbelievableflavour** [comment]
I added Houston Ci and everything seems fine, send a new release to dashboard. Should be on Juno on the store soon.

**Comment by peteruithoven** [comment]
Awesome! Thanks!
Seeing that Houston gave no errors I thought it would be nice to try compiling it myself and trying it on Juno (where I just upgraded to), but I can't get it to compile yet. I've asked a question here: 
https://elementaryos.stackexchange.com/questions/16271/using-cmake-on-juno
I'll let you know if I run into something interesting.

**Comment by unbelievableflavour** [comment]
Thnx, i don't have Juno yet so that would be of great help.

**Comment by peteruithoven** [comment]
Figured out the building. Seems okay except for a minor layout issue on the Install page. Weirdly enough there is no issue on the Info page. 
Left is Loki, right is Juno.
## Install
![install](https://user-images.githubusercontent.com/523210/45657225-b7499800-bae9-11e8-9744-c74b6229eafd.png)
## Info
![info](https://user-images.githubusercontent.com/523210/45657222-b7499800-bae9-11e8-8912-adfd0978f8a9.png)
## Home
![home](https://user-images.githubusercontent.com/523210/45657220-b7499800-bae9-11e8-8f4c-8c044b48c8cd.png)
## Updates
![updates](https://user-images.githubusercontent.com/523210/45657221-b7499800-bae9-11e8-8646-90d570936f25.png)
## In progress
![in progress](https://user-images.githubusercontent.com/523210/45657223-b7499800-bae9-11e8-98be-fcde319d4b7c.png)

**Comment by unbelievableflavour** [comment]
So whats the issue. The font size? Also, did you build it yourself? or downloaded from the store. If you build it yourself, could you check if it is available in the store now too?

**Comment by unbelievableflavour** [comment]
Oh the issue is that another applications hover text falls over Snaptastic application?

**Comment by peteruithoven** [comment]
I was referring to the following minor layout issue. The application title seems to be have a slightly larger margin on it's left and right.
![screenshot from 2018-09-18 11-25-09](https://user-images.githubusercontent.com/523210/45677917-a161c480-bb35-11e8-9c0e-b208de57730e.png)

I build it myself, but it's now also available in the store.

**Comment by unbelievableflavour** [comment]
Ah ok, lets create a separate issue for that and close this issue. As Snaptastic is now available on the store in Juno.

**Comment by peteruithoven** [comment]
Good point
