### ISSUE TITLE
Support installing apps from channels other than stable.

### ISSUE THREAD

**Issue by arshubham** [bartzaalberg/snaptastic#48]
![image](https://user-images.githubusercontent.com/14235191/45916105-23c3ee80-be7e-11e8-8e7d-2f694dfec459.png)

**Comment by unbelievableflavour** [comment]
Could you give a bit of description in your issues? I can't reproduce them if you don't explain how you got the issue :)

**Comment by arshubham** [comment]
This issue happens when clicking View in Desktop Store on Snapcraft store on channels other than stable.
![image](https://user-images.githubusercontent.com/14235191/51034684-8d067380-15cd-11e9-855b-d1db8ec689a2.png)

**Comment by peteruithoven** [comment]
You can select to install another channel on snapcraft.io:
![screen record from 2019-01-11 13 51 25 2x](https://user-images.githubusercontent.com/523210/51034916-9c26fa80-15a8-11e9-84b0-23ea0deb8395.gif)

Gotta love [Screen Recorder](https://appcenter.elementary.io/com.github.mohelm97.screenrecorder).

**Comment by unbelievableflavour** [comment]
Ah Nice! Will check that later.

**Comment by unbelievableflavour** [comment]
Fixed it in release 0.6.0. Should be live soon.

**Comment by unbelievableflavour** [comment]
It's live. Please test.
