### ISSUE TITLE
Don't launch new instance for every app install for snapstore

### ISSUE THREAD

**Issue by arshubham** [bartzaalberg/snaptastic#49]

**Comment by unbelievableflavour** [comment]
Its been released. Please test.

**Comment by arshubham** [comment]
Snaptastic now won't even open the app after clicking view in desktop store. I tried adding by opening the app first but got the same result.

**Comment by unbelievableflavour** [comment]
Problem is found and solved here. https://github.com/bartzaalberg/snaptastic/issues/61

**Comment by unbelievableflavour** [comment]
It's been released. Please test and close the issue if it's ok

**Comment by unbelievableflavour** [comment]
Closing this.
