### ISSUE TITLE
Remember window state

### ISSUE THREAD

**Issue by arshubham** [bartzaalberg/snaptastic#50]

**Comment by unbelievableflavour** [comment]
Do you mean you want to start on the last page you where? Because i wouldn't want to start on an app i last installed. I could however save state for list-view and welcome-view. So that when visiting list-view it saves list-view.

**Comment by arshubham** [comment]
No, I mean windows size and position on the desktop. Currently it is reset in each session.

**Comment by peteruithoven** [comment]
In that case https://github.com/bartzaalberg/snaptastic/issues/58 was a duplicate of this issue?

**Comment by unbelievableflavour** [comment]
Yup. Closing this.
