### ISSUE TITLE
Application icons

### ISSUE THREAD

**Issue by junocomp** [bartzaalberg/snaptastic#52]
Would it be possible to show the application icons for all the snaps that are installed?

**Comment by unbelievableflavour** [comment]
I'm sorry, i tried to show the application icons. But the get_icon function gives me null. I also tried the get_screenshots() function but that gives me an empty array. @robert-ancell  do you maybe have an idea what can be wrong?

**Comment by robert-ancell** [comment]
Are you using get_icon () from the result of a get_snap () or a find () call? The former gets the locally installed snap information which *may* contain an icon file (something like /snap/*name*/current/snap/gui/*name*.png). The latter gets the icon information from the store, which is more consistently available (it will be a URL). In the case of gnome-software we always query the store for the icons.

**Comment by unbelievableflavour** [comment]
I use this function to get the list. https://valadoc.org/snapd-glib/Snapd.Client.list_sync.html And i use
https://valadoc.org/snapd-glib/Snapd.Client.find_sync.html to get specific packages. So `list_sync` and `find_sync`. I just tried them both again and the both give me null.

**Comment by robert-ancell** [comment]
To confirm, when you call get_icon() on the object you get back from Snapd.Client.find_sync() you get nothing? Which snap is this?

**Comment by unbelievableflavour** [comment]
I don't know why i didn't work the times before. Must have overlooked something... But huraayyyy! i got it working! It will be available in the next release.

**Comment by bartzaalberg** [comment]
It's live. Please test

**Comment by unbelievableflavour** [comment]
Its live, please test and close if it's ok.

**Comment by peteruithoven** [comment]
Works great, but I noticed that the icons's are a bit blurry. Could be caused by my HiDPI screen?
![screenshot from 2019-01-23 14 51 16](https://user-images.githubusercontent.com/523210/51611004-78f03980-1f1e-11e9-94b2-758d1f2ad236.png)
![screenshot from 2019-01-23 14 51 38](https://user-images.githubusercontent.com/523210/51611036-89081900-1f1e-11e9-90ff-e79e17fea4fc.png)

**Comment by unbelievableflavour** [comment]
I have no idea. It looks fine on my screen.. Any ideas on what i can do about it?

**Comment by unbelievableflavour** [comment]
Ok, I made sure icon biggest icon that is found is used. Please check If it's fixed in master. If it's still an issue, please create a separate issue.
