### ISSUE TITLE
Packages don't work

### ISSUE THREAD

**Issue by KCS007** [bartzaalberg/snaptastic#54]
They install (with no clear indication they are installed), and if you click "open" you get "There was an error spawning the process. Details", "Failed to execute child process “name” (No such file or directory)". No shortcuts show anywhere in the UI. Elementary 5.0 stable.

**Comment by KCS007** [comment]
And Snappy Backend from the non-curated store works great.

**Comment by fabiopicchi** [comment]
Hi! I just did a pull request fixing this issue :)

@bartzaalberg I can't really understand why my change didn't pass the tests, could you please check it out?

**Comment by unbelievableflavour** [comment]
I added it to the next release. @fabiopicchi thanks!

**Comment by unbelievableflavour** [comment]
@fabiopicchi the new version is released. Could you check if your problem is fixed?

**Comment by fabiopicchi** [comment]
It is working! :)

**Comment by unbelievableflavour** [comment]
Nice! Closing this.
