### ISSUE TITLE
It doesn't remember the window size.

### ISSUE THREAD

**Issue by sprite-1** [bartzaalberg/snaptastic#58]
It keeps taking up a large amount of space whenever it opens. Can you implement some way for it to retain the size I had the window at beforehand?

**Comment by unbelievableflavour** [comment]
Should this be done by the application itself? Or should the OS remember the window size.

**Comment by sprite-1** [comment]
Good question... but every other app from the AppCenter seems to retain the last size they were in aside from yours though 🤔

**Comment by unbelievableflavour** [comment]
Hmm.. That's odd. I will have a look when i have some spare time.

**Comment by sprite-1** [comment]
Okay thank you! I don't know how eOS handles window sizes and positions, if it delegates it to the apps themselves or if they handle it themselves but every other app I've used from the AppCenter remembers the size and position so when I tried out yours, it stuck out as the odd one out of everything else.

**Comment by peteruithoven** [comment]
I'm afraid you need to do this manually: 
https://elementary.io/docs/code/reference#saving-window-state
https://elementary.io/docs/code/getting-started#saving-state

I'm hoping for something in Granite that we can reuse in the future: https://github.com/elementary/granite/issues/224

**Comment by unbelievableflavour** [comment]
Ah ok, Well thnx @peteruithoven . At least it's documented nicely.

**Comment by sprite-1** [comment]
With the latest update, the app window permanently opens on this particular location on the screen

![image](https://user-images.githubusercontent.com/33685433/51582300-6538d900-1f06-11e9-9a35-453800d4fe2b.png)

**Comment by unbelievableflavour** [comment]
Is that an issue? And if so, shouldn't it be a separate issue?

**Comment by sprite-1** [comment]
I feel like it's still related to the main problem of the app not saving the last window size and position

**Comment by unbelievableflavour** [comment]
Ah i didn't see that this issue was also about positioning. Sorry!

**Comment by sprite-1** [comment]
No worries 👍

**Comment by unbelievableflavour** [comment]
Added it. Size, maximized, and position are now saved. Should be available in next release.

**Comment by unbelievableflavour** [comment]
It's been released. Please test and close the issue if it's ok

**Comment by sprite-1** [comment]
it's working properly now, thanks! :tada: :tada:
