### ISSUE TITLE
Investigate performance issues

### ISSUE THREAD

**Issue by unbelievableflavour** [bartzaalberg/snaptastic#59]
Icons are loaded sync now which slows down the application. Try to do this async.

**Comment by peteruithoven** [comment]
You could use Granite's [AsyncImage](https://github.com/elementary/granite/blob/master/lib/Widgets/AsyncImage.vala). It's for example used in the Applications menu. 
Be aware of this issue though: https://github.com/elementary/granite/issues/223

**Comment by unbelievableflavour** [comment]
I actually already use AsyncImage. I'm thinking the problem isn't the images but getting the snaps from the web. Changing issue title

**Comment by unbelievableflavour** [comment]
Fixed in master. Now closing
