### ISSUE TITLE
Opening with snap url issue

### ISSUE THREAD

**Issue by peteruithoven** [bartzaalberg/snaptastic#63]
When opening Snaptastic with a snap url from snapcraft.io it looks like it only momentarily opens the snap install page, but than switches back to the Home page. 
When clicking the *View in Desktop store* button again it opens the snap install page again. 

![screen record from 2019-01-23 11 51 39](https://user-images.githubusercontent.com/523210/51601848-b8f6f280-1f05-11e9-8624-2051e0f11ac3.gif)

**Comment by unbelievableflavour** [comment]
Fixed in master!

**Comment by peteruithoven** [comment]
Works! Thanks.

**Comment by SandroCristiano** [comment]
I'm having a similar issue. Whenever I try to install from snapcraft.io, snaptastic opens, shows me the install dialog and after I click install nothing happens for a while and then snaptastic closes and the snap isn't installed. It works the other way around, though. If I install a snap using the command line, it installs normally and is shown in the snaptastic window.
