### ISSUE TITLE
Add Portuguese Translations

### ISSUE THREAD

**Issue by aimproxy** [bartzaalberg/snaptastic#76]
Hi, I'm a native Portuguese, I saw your app dontsen't have translated in PT yet, can I make a PR with Portuguese Translations?

**Comment by unbelievableflavour** [comment]
Please do! I'll make a release for it if you add it :)

**Comment by aimproxy** [comment]
Yeah I will do this probably today, you can assignee me!

**Comment by unbelievableflavour** [comment]
Are you still gonna?

**Comment by aimproxy** [comment]
Sorry men, I complete forgot that one! I should close this, I'm too busy at work.
