### ISSUE TITLE
Display Icons in Applications Menu

### ISSUE THREAD

**Issue by aimproxy** [bartzaalberg/snaptastic#77]
Hi, when I install an snap app, I can't retrieve it from application menu! and also the icons are blurry on FHD Monitor!

**Comment by peteruithoven** [comment]
Please don't use "!"'s, that comes across as quite rude. It might do you well to read an article like [Why open source developers are burning out: No respect](https://www.techrepublic.com/article/why-open-source-developers-are-burning-out-no-respect/)

Snaptastic uses Snapd to install apps so I don't think it can help you with that issue. 
Snapd: https://github.com/snapcore/snapd

**Comment by aimproxy** [comment]
I think we can make something like when the app is successful installed create a `.desktop` file on `/usr/share/applications/` because snapd installation directory is not bean read by application menu on elementaryOS. Don't interpret "!"s as rude, we are on a open source community, I'm not rude with anyone .

**Comment by peteruithoven** [comment]
Are you sure you've tried restarting your computer after installing Snaptastic (snapd)? Also see: https://docs.snapcraft.io/installing-snap-on-elementary-os

**Comment by aimproxy** [comment]
It's working know, thanks I diden't know about it!
