### ISSUE TITLE
Wrong language in interface

### ISSUE THREAD

**Issue by RubenSibon** [bartzaalberg/snaptastic#79]
The system-wide language set in Elementary OS is Dutch, but in Snaptastic I see what appears to be Lithuanian (?). What is going on?

Snaptastic is the only app on my system that has this issue.

I tried re-setting the system-wide language, rebooting and reinstalling the app. Does not help.

![Schermafdruk van 2020-04-21 20-42-39](https://user-images.githubusercontent.com/7290629/79901808-b63cc300-8410-11ea-8616-ad9de02822a3.png)

**Comment by unbelievableflavour** [comment]
Hi, just fixed it. A new release will be pushed soon. You can test it already by building the latest master. Thnx for letting me know! Must have gone wrong in some merge conflicts I fixed a while ago.

**Comment by unbelievableflavour** [comment]
Closing this. It has been released.
