### ISSUE TITLE
Handle snap URLs

### ISSUE THREAD

**Issue by danirabbit** [bartzaalberg/snaptastic#9]
Here's a relevant commit where apt url support was added in AppCenter: https://github.com/elementary/appcenter/commit/34e6785f3ce02a48b6215bd3482cdb109ed6e80a

**Comment by unbelievableflavour** [comment]
Thanks! Will look into that Tomorrow :)

**Comment by unbelievableflavour** [comment]
Hi, im trying to get this to work but i won't get any reaction from browsers. (chrome/firefox) Could you maybe have a look and see what i'm doing wrong?
Commit = https://github.com/bartzaalberg/snaptastic/commit/64724703e4327484d275c2fe6274521a5461ce18

**Comment by unbelievableflavour** [comment]
@danrabbit could you please have a look?

**Comment by peteruithoven** [comment]
Maybe @davidmhewitt could help, he build in magnet link support in Torrential:
https://github.com/davidmhewitt/torrential/commit/7a0884171cd5dc4c111860b99b6609ca27022c75

**Comment by davidmhewitt** [comment]
Have you tried a `update-desktop-database /usr/share/applications` after installing your new desktop file into that folder?

**Comment by unbelievableflavour** [comment]
oh wow. That actually worked immediately. Thanks :) Do i need to integrate this in the app or does that happen automatically after installing an app from appcenter?

**Comment by davidmhewitt** [comment]
I believe the package manager should do this automatically when your application is installed through apt or the AppCenter. 

I haven't had to do anything special with Torrential to get my magnet links to work, it's just something to keep in mind when your `.desktop` file is manually installed using CMake.

**Comment by unbelievableflavour** [comment]
Thanks. I added that to the readme as a reminder.
